import discord
import random
import os
from discord.ext import commands

client = commands.Bot(command_prefix='+')

@client.event
async def on_ready():
    await client.change_presence(status=discord.Status.dnd, activity=discord.Game('Truth or Dare'))
    print('Bot is ready')

@client.event
async def on_command_error(ctx, error):
    if isinstance(error, commands.CommandNotFound):
        return
    raise error

@client.command()
async def truth(ctx):
    truth = ['When was the last time you lied?',
             'When was the last time you cried?',
             "What's your biggest fear?",
             "What's your biggest fantasy?",
             'Do you have any fetishes?',
             "What's something you're glad your mum doesn't know about you?",
             'Have you ever cheated on someone?',
             "What's the worst thing you've ever done?",
             "What's a secret you've never told anyone?",
             'Do you have a hidden talent?',
             'Who was your first celebrity crush?',
             'What are your thoughts on polyamory?',
             "What's the worst intimate experience you've ever had?",
             "What's the best intimate experience you've ever had?",
             'Have you ever cheated in an exam?',
             "What's the most drunk you've ever been?",
             'Have you ever broken the law?',
             "What's the most embarrassing thing you've ever done?",
             "What's your biggest insecurity?",
             'Have you ever stayed friends with someone because it benefitted you beyond just the friendship?',
             "What's the biggest mistake you've ever made?",
             "What's the most disgusting thing you've ever done?",
             'Who would you like to kiss in this room?',
             "What's one thing you hate people knowing about you?",
             "What's the worst thing anyone's ever done to you?",
             "What's the best thing anyone's ever done for you?",
             'Have you ever had a run in with the law?',
             "What's your worst habit?",
             "What's the most embarrassing thing you've done in a taxi?",
             "What's the worst thing you've ever said to anyone?",
             'Have you ever peed in the shower?',
             "What's the strangest dream you've had?",
             "Have you ever been caught doing something you shouldn't have?",
             "What's the worst date you've been on?",
             "What's the best date you've been on?",
             "What happened on the latest night out you've ever had?",
             "What's your biggest regret?",
             "What's the biggest misconception about you?",
             'Have you ever said something you regret about someone in this room?',
             "What's one thing you wish people knew about you?",
             "Where's the weirdest place you've had sex?",
             'Why did your last relationship break down?',
             'Have you ever lied to get out of a bad date?',
             "What's the most trouble you've been in?",
             'When did you last have sex outside?',
             "What's the worst thing you've lied about?",
             "What's one thing you wish you'd lied about?",
             "What's the best piece of advice you've been given?",
             "What's the most you've spent on a night out?",
             'Name a time you think you were a bad partner',
             "What's your guilty pleasure?",
             "What's one thing you only do when you're alone?",
             "If you had to get back with an ex, who would you choose?",
             "If you had to cut one friend out of your life, who would it be?",
             'Do you have a favourite friend?',
             'Do you have a favourite sibling?',
             "What's the strangest rumour you've heard about yourself?",
             "What's your biggest turn on?",
             "What's the silliest reason you've left a club early?",
             "What have you purchased that's been the biggest waste of money?",
             'If you could swap lives with someone in this room, who would it be?',
             'What Was Your First Kiss Like?',
             'What Is Your Least Favorite Thing About Your Best Friend?',
             "Have You Ever Committed A Crime? If So, What Was It?",
             'Have You Ever Cried From Watching A TV Show Or A Movie?',
             'What Would You Do With A Million Dollars?',
             'What Is The Most Embarrassing Thing That Your Parents Have Caught You Doing?',
             'When Was A Time That You Completely Lost It?',
             "If You Could Have Someone Else’s Life For One Day, Who Would It Be?",
             'If You Could Say Anything To One Person In Your Life Without Any Consequences, What Would It Be?',
             'Have You Ever Let Someone Take The Blame For Something You Did? What Happened?',
             "What’s Something In Your Web Browsing History That You’d Be Embarrassed If Someone Saw?",
             "Have You Ever Shared A Secret You Shouldn’t Have, Or Promised You Wouldn’t?",
             'How Many Romantic Interests Do You Think You Will Have For The Rest Of Your Life?',
             'Was There Ever A Time In Your Life That You Thought You Were Going To Die?',
             'What Is Your Worst Childhood Memory?',
             'What Do You Do When You Are Alone And No One Is Watching You?',
             "What Kids’ Movie Do You Still Secretly Watch Over And Over?",
             'What Is One Thing That You Have Always Wanted To Do But Have Not Gotten Around To It Yet?',
             'What Is The Craziest Event That You Have Ever Been To?',
             'What Is The Most Embarrassing Thing That Has Happened To You This Year?',
             'What Is Your Secret Talent If You Have One?',
             'What Is The Most That You Have Ever Had To Drink?',
             'What Book Are You Embarrassed To Have Read?',
             'What Do You Eat When You Can Choose Anything And No One Is Around To See?',
             'What is one secret you are hiding from your mom?',
             'Have you ever stalked someone on Facebook or Instagram?',
             'What would you buy me if I gave you $50?',
             'If I went through your room, what is something I would be shocked to find?',
             'Have you ever prank called a friend?',
             'How many selfies do you take a week?',
             'How many boy/girl contacts do you have on your phone?',
             'Have you ever fallen in front of your crush?',
             'Do you currently have a crush on anyone?',
             'Is there anything in your life that you would change?',
             'Who do you hate and why?',
             'What is your biggest pet peeve?',
             'How many people have you kissed?',
             'Do you cover your eyes during the scary parts of a movie?',
             'Have you ever practiced kissing the mirror?',
             'What was your most embarrassing moment in public?',
             'What is your guilty pleasure?',
             'Do you talk in your sleep?',
             'Do you drool in your sleep?',
             'What is your go-to song to sing in the shower?',
             'Have you ever blamed your fart on someone else?',
             'Have you ever farted in an elevator?',
             'What was your favorite childhood video game?',
             'Would you rather have no heating or A/C or no internet?',
             'If you suddenly became invisible what would you do?',
             'Would you rather let your dog eat out of your mouth or eat food out of a trash can?',
             'Have you ever played a prank on your parents?',
             'Would you rather be caught picking your nose or picking a wedgie?',
             'Describe the strangest dream you’ve ever had.',
             'Do you have any silly nicknames?',
             'If you could have any superpower, what would it be?',
             'If you could change places with a celebrity for a day, who would you choose?',
             'What is your favorite type of ice cream?',
             'Are you an early bird or a night owl?',
             'If you could travel anywhere in the world, where would you go?',
             'Have you ever eaten something off the floor?',
             'What is your favorite holiday?',
             'Describe what your crush looks like',
             'If you could change anything about yourself, what would it be?',
             'If you had to kiss a Disney character, who would you choose?']
    await ctx.send(random.choice(truth))

@client.command()
async def dare(ctx):
    dare = ['Show the most embarrassing photo on your phone',
            'Show the last five people you texted and what the messages said',
            'Let the rest of the group DM someone from your Instagram account',
            'Eat a raw piece of garlic',
            'Do 100 squats',
            'Let the group look in your Instagram DMs',
            'Show us your screen time report',
            'Keep three ice cubes in your mouth until they melt',
            'Say something dirty to the person on your left',
            'Give a foot massage to the person on your right',
            'Put 10 different available liquids into a cup and drink it',
            'Yell out the first word that comes to your mind',
            'Give a lap dance to someone of your choice',
            'Remove four items of clothing',
            'Like the first 15 posts on your Facebook newsfeed',
            'Eat a spoonful of mustard',
            "Keep your eyes closed until it's your go again",
            'Send a sext to the last person in your phonebook',
            'Show your orgasm face',
            'Seductively eat a banana',
            "Empty out your wallet/purse and show everyone what's inside",
            'Do your best sexy crawl',
            'Pretend to be the person to your right for 10 minutes',
            'Eat a snack without using your hands',
            'Say two honest things about everyone else in the group',
            'Twerk for a minute',
            'Try and make the group laugh as quickly as possible',
            'Try to put your whole fist in your mouth',
            'Let another person in the group touch up your makeup',
            'Tell everyone an embarrassing story about yourself',
            'Try to lick your elbow',
            'Say everything in a whisper for the next 10 minutes',
            "Smell another player's armpit",
            'Talk in an American accent for the rest of the evening',
            'Do your best celebrity impression',
            'Play air guitar for 2 minutes straight',
            'Post the oldest selfie on your phone on Instagram Stories',
            'Tell the saddest story you know',
            'Howl like a wolf for two minutes',
            'Dance without music for two minutes',
            'Pole dance with an imaginary pole',
            'Let someone else tickle you and try not to laugh',
            'Put as many snacks into your mouth at once as you can',
            'Scroll through your phone book until someone says stop. You either have to call or delete that person.',
            'Put your clothing on backwards for the rest of the evening',
            'Try and make yourself cry in front of the group',
            'Tell the group two truths and a lie, and they have to guess which one the lie is',
            'Show off your secret talent',
            'Attempt to impersonate everyone in the room',
            'Reply to the first five Instagram Stories on your timeline',
            "Share the first celebrity on your timeline's Instagram to your Story",
            'Put on as many layers as possible in 60 seconds',
            'Fill your mouth with drink and gargle your answer to the next Truth',
            'Smile as widely as you can and hold it for two minutes',
            'Hold your drink with two hands for the rest of the evening',
            'Attempt the first TikTok dance on your for you page',
            'Sit on the floor for the rest of the evening',
            'Give a personalised insult to everyone in the room',
            'Make up a song and voice record yourself singing it. Send it to me when you’re done',
            'Video yourself eating a tablespoon of butter and send it to me',
            'Lick your own armpit. Record yourself',
            'Prank call someone and try to talk for 15 minutes straight. Take a screenshot of the call',
            'Eat a spoonful of any condiment of my choosing',
            'Tell your crush you like them over text. Screenshot the conversation',
            'Wrap your head with toilet paper like a mummy, take a picture, and make it your profile pic',
            'Use a picture of me as your phone background for 3 days',
            'Text a friend and tell them their hair is on backward',
            'Call someone and confess your new love of Justin Bieber',
            'Send me the link of the last YouTube video you watched',
            'Write a short love poem',
            'Find some lipstick and put it on',
            'Write my name somewhere on your body (where it can be hidden) with a permanent marker',
            'Do a sexy dance with just one leg',
            'Voice record yourself singing your favorite love song and send it to me',
            'Send me the most unflattering picture of yourself on your phone',
            'Read me the first email in your inbox',
            'Video call me or record yourself dancing for 1 minute with no music',
            'Send me a screenshot of your text inbox without deleting anything',
            'Tell me all of the contents of your purse/wallet',
            'Take a video of yourself drinking pickle juice',
            'Go outside and do the chicken dance where people can see you for 1 minute',
            'Dip a bar of soap in sauce and lick it',
            'Go as far down in the splits as you can',
            'Write a status on Facebook praising me',
            'Do the macarena for 2 minutes straight',
            'Close your eyes and write a text without looking. Send it to someone random and screenshot the conversation for proof',
            'Write a break-up text message and send it to someone random in your contacts. Take a screenshot for proof',
            'Wear all your clothing inside-out for an hour',
            'Take a video of yourself drinking water like a dog',
            'Fill your mouth full of water and say your full name. Take a video and send it',
            'Call your crush and flirt with him/her',
            'Dial a random number and make meaningless conversation for 2 minutes',
            'Do 25 situps without stopping',
            'Take a video of yourself imitating a celebrity',
            'Crack two eggs on your head then take a selfie',
            'What’s your deepest secret?',
            'Call me and say my name in a loud voice',
            'Send a screenshot of your search history from the past two days',
            'Record a video of you singing a song with a mouthful of peanut butter',
            'Call a stranger and tell them a secret',
            'Call your mom and tell her you can’t find a boyfriend/girlfriend in a panicked voice',
            'Color one of your front teeth black and take a selfie (eyeliner works for this!)',
            'Send me the 11th picture in your photo gallery',
            'In what subject did you get the worst marks and when?',
            'Send me your favorite TikTok/YouTube video',
            'Put flour all over your face and take a selfie',
            'Send me a picture of your first crush']
    await ctx.send(random.choice(dare))

client.run(os.environ['Discord'])